//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostlyGame.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhostlyGame.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Worlds.
        /// </summary>
        internal static string AllWorlds {
            get {
                return ResourceManager.GetString("AllWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are BFR VOP Values Correct?.
        /// </summary>
        internal static string AreBFRVOPValuesCorrect {
            get {
                return ResourceManager.GetString("AreBFRVOPValuesCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Menu.
        /// </summary>
        internal static string BackToMenu {
            get {
                return ResourceManager.GetString("BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMG.
        /// </summary>
        internal static string EMG {
            get {
                return ResourceManager.GetString("EMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How to Play Ghostly+ Game.
        /// </summary>
        internal static string HowToPlayGhostlyGame
        {
            get
            {
                return ResourceManager.GetString("HowToPlayGhostlyGam", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to control the game using.
        /// </summary>
        internal static string IWantToControlTheGameUsing {
            get {
                return ResourceManager.GetString("IWantToControlTheGameUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        internal static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left VOP.
        /// </summary>
        internal static string LeftVOP {
            get {
                return ResourceManager.GetString("LeftVOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Completed.
        /// </summary>
        internal static string LevelCompleted {
            get {
                return ResourceManager.GetString("LevelCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Game ....
        /// </summary>
        internal static string LoadingGame {
            get {
                return ResourceManager.GetString("LoadingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maze.
        /// </summary>
        internal static string Maze {
            get {
                return ResourceManager.GetString("Maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Level.
        /// </summary>
        internal static string NextLevel {
            get {
                return ResourceManager.GetString("NextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Perceived Exertion.
        /// </summary>
        internal static string RatedPerceivedExertion {
            get {
                return ResourceManager.GetString("RatedPerceivedExertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right VOP.
        /// </summary>
        internal static string RightVOP {
            get {
                return ResourceManager.GetString("RightVOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Patient.
        /// </summary>
        internal static string SelectPatient {
            get {
                return ResourceManager.GetString("SelectPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Level.
        /// </summary>
        internal static string SelectTheLevel {
            get {
                return ResourceManager.GetString("SelectTheLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The World.
        /// </summary>
        internal static string SelectTheWorld {
            get {
                return ResourceManager.GetString("SelectTheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot.
        /// </summary>
        internal static string Shoot {
            get {
                return ResourceManager.GetString("Shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Maze.
        /// </summary>
        internal static string SimpleMaze {
            get {
                return ResourceManager.GetString("SimpleMaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Space.
        /// </summary>
        internal static string SimpleSpace {
            get {
                return ResourceManager.GetString("SimpleSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Switch &gt;.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        internal static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the halves of the screen to.
        /// </summary>
        internal static string TouchTheHalvesOfTheScreenTo {
            get {
                return ResourceManager.GetString("TouchTheHalvesOfTheScreenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Instructions.
        /// </summary>
        internal static string WatchInstructions {
            get {
                return ResourceManager.GetString("WatchInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
